http_interactions:
  - request:
      method: DELETE
      uri: https://api.cloudflare.com/client/v4/accounts/abc123/storage/kv/namespaces/ns-1/bulk
    response:
      status: 200
      headers:
        content-type: application/json
      body:
        string: |
          {"success": true, "errors": [], "messages": [],
           "result": {"successful_key_count": 2, "unsuccessful_keys": []}}
    recorded_at: 2026-05-20 18:07:49
recorded_with: VCR-vcr/2.1.0
